### ISSUE TITLE
Shared parameters get picked up as a method

### ISSUE THREAD

**Issue by acossta** [synx-ai/openapi2md#4]
When you have shared parameters between methods ( as shown below), parameters taken as a method and not shown in the individual method pages

```
/Users/{userId}:
    parameters:
      - in: path
        name: userId
        required: true
        schema:
            type: String
        description: "The User's ID."
    get:
      summary: 'Returns details about a particular User'
```
